relative_url/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('index',views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

relative_url/relative_url/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

relative_url/myapp/models.py
from django.db import models

# Create your models here.

relative_url/myapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"myapp/index.html",context={'yeap':'WELCOM'})

def other(request):
    return render(request, 'myapp/other.html')

def relative(request):
    return render(request, 'myapp/relative_template_tag.html')

relative_url/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>template inheritance</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top ">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'myapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside of this block will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

relative_url/templates/myapp/index.html
<!DOCTYPE html>
{% extends 'myapp/base.html'%}
  {% block body_block %}
{% load staticfiles %}
    <h2>{{ yeap }}</h2>
    <h1>HOME PAGE</h1>
  {% endblock %}

relative_url/templates/myapp/other.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
  {% block body_block %}
    <h1>WELCOME TO THE OTHER PAGE</h1>
    <h2>This is an example of template inheritance</h2>

  {% endblock %}

relative_url/templates/myapp/relative_template_tag.html
<!DOCTYPE html>
{% extends 'myapp/base.html'%}
  {% block body_block %}
    <h1>WELCOME TO RELATIVE TEMPLATE TAG</h1>
    <a href="{% url 'myapp:other' %}">OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN LINK</a>
    <a href="{% url 'index' %}">HOME PAGE</a>
  {% endblock %}